version: "3.7"

services:

  gpl:
    build: ./generative-pseudo-labeling
    env_file:
      - .env
    ports:
      - 8003:8000


  ui:
    build: ./ui
    env_file:
      - .env
    ports:
      - 8501:8501
