version: "3"

services:
  # main:
  #   build: ./
  #   restart: always
  #   ports:
  #     - 8000:8000

  demo:
    build: ./demo
    restart: always
    ports:
      - 8001:8000

  es01: 
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: es01
    environment:
      - "discovery.type=single-node"
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports: 
      - 9200:9200
    networks:
      - elastic

  kibana:
    depends_on: 
      - es01
    image: docker.elastic.co/kibana/kibana:7.9.3
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - 5601:5601
    networks:
      - elastic
networks:
  elastic:
volumes:
  data01:
    driver: local

