version: "3"

services:
  gpl:
    build: ./adapt-bio
    ports:
      - 8002:8000
    env_file:
      - ./adapt-bio/.env
    depends_on: 
      - es01
    volumes:
      - gpl:/usr/share/mlruns

  ui:
    build: ./ui
    env_file:
      - .env
    ports:
      - 8501:8501

  demo:
    build: ./demo
    ports:
      - 8001:8000
    depends_on: 
      - es01

  es01: 
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: es01
    environment:
      - "discovery.type=single-node"
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports: 
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - 5601:5601
    depends_on: 
      - es01

volumes:
  data01:
    driver: local
  gpl:
    driver: local

